#!/usr/bin/env python3
"""Write Zen session spaces/pins into flake profile dirs (spaces.nix, pins.nix).

Default target directory under home/.../zen/profiles/ is chosen from the host unless
ZEN_OUTPUT_PROFILE is set. On NixOS, requesting the alternate profile name is remapped
to the primary profile unless ZEN_IGNORE_OUTPUT_PROFILE_NIXOS_GUARD=1 (alias:
ZEN_SYNC_CAYA_ON_NIXOS=1 for compatibility).
"""

import os
import re
import sys
import uuid
from difflib import unified_diff
from datetime import datetime

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_FLAKE_ROOT = os.path.dirname(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
sys.path.insert(0, _SCRIPT_DIR)
from extract_pinned_tabs import (  # noqa: E402
    host_is_nixos,
    load_pinned_per_space,
    nix_escape,
    slug,
)

# Subdirs of home/shared/apps/browsers/zen/profiles/ (see zen/default.nix).
_FLAKE_ZEN_PROFILE_PRIMARY = "default"
_FLAKE_ZEN_PROFILE_ALTERNATE = "caya"

_SYNC_TOOL = "zen_session.py sync (scripts/zen-session)"


def _truthy_env(name):
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes")


def _nixos_alternate_profile_guard_disabled():
    """Allow writing the alternate flake profile from NixOS when explicitly opted in."""
    return _truthy_env("ZEN_IGNORE_OUTPUT_PROFILE_NIXOS_GUARD") or _truthy_env(
        "ZEN_SYNC_CAYA_ON_NIXOS"
    )


def _resolved_flake_profile_dirname():
    raw = os.environ.get("ZEN_OUTPUT_PROFILE")
    if raw is not None:
        v = raw.strip()
        if v:
            if (
                host_is_nixos()
                and v == _FLAKE_ZEN_PROFILE_ALTERNATE
                and not _nixos_alternate_profile_guard_disabled()
            ):
                return _FLAKE_ZEN_PROFILE_PRIMARY
            return v
    return (
        _FLAKE_ZEN_PROFILE_ALTERNATE
        if sys.platform == "darwin"
        else _FLAKE_ZEN_PROFILE_PRIMARY
    )


_TARGET_PROFILE_DIR = os.path.join(
    _FLAKE_ROOT,
    "home",
    "shared",
    "apps",
    "browsers",
    "zen",
    "profiles",
    _resolved_flake_profile_dirname(),
)


def _backup(path):
    if not os.path.isfile(path):
        return
    stamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    backup_path = f"{path}.{stamp}.bak"
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    with open(backup_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Backed up to {os.path.basename(backup_path)}", file=sys.stderr)


def _render_spaces(spaces_list):
    used = set()
    lines = []
    for i, s in enumerate(spaces_list):
        name = (s.get("name") or "").strip() or "Default"
        sid = s.get("id") or ""
        icon = str(s.get("icon") or "").strip()
        pos = s.get("position")
        if pos is None or (isinstance(pos, (int, float)) and pos == 0):
            pos = 1000 + i
        key = nix_escape(name)
        if key in used:
            key = nix_escape(f"{name} ({sid[:8]})")
        used.add(key)
        lines.append(
            '    "'
            + key
            + '" = { id = "'
            + sid
            + '"; icon = "'
            + nix_escape(icon)
            + '"; position = '
            + str(int(pos))
            + "; };"
        )
    body = "\n".join(lines)
    return (
        f"# Zen workspaces. Generated by {_SYNC_TOOL}.\n{{ ... }}: {{\n  spacesForce = true;\n  spaces = {{\n"
        + body
        + "\n  };\n}\n"
    )


def _write_spaces(spaces_list):
    path = os.path.join(_TARGET_PROFILE_DIR, "spaces.nix")
    _backup(path)
    content = _render_spaces(spaces_list)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {path}", file=sys.stderr)


def _space_id_to_nix_key(spaces_list):
    used = set()
    out = {}
    for s in spaces_list:
        name = (s.get("name") or "").strip() or "Default"
        sid = s.get("id") or ""
        key = nix_escape(name)
        if key in used:
            key = nix_escape(f"{name} ({sid[:8]})")
        used.add(key)
        out[sid] = key
    return out


def _render_pins(windows, folders, spaces_list):
    space_to_key = _space_id_to_nix_key(spaces_list)
    seen_urls_essential = set()
    seen_keys_all = set()
    pos_essential = 101
    pos_pin = 201
    entries = []

    for group in windows:
        for p in group["pins"]:
            if not p.get("isEssential"):
                continue
            url = p["url"]
            if url in seen_urls_essential:
                continue
            seen_urls_essential.add(url)
            title = p.get("title") or slug(None, url)
            key = nix_escape(title or slug(None, url))
            c = 0
            while key in seen_keys_all:
                c += 1
                key = nix_escape(f"{title or 'Essential'}_{c}")
            seen_keys_all.add(key)
            pin_id = p.get("tabId") or str(uuid.uuid4()).lower()
            if not re.match(r"^[a-f0-9\-]{36}$", str(pin_id)):
                pin_id = str(uuid.uuid4()).lower()
            frag = (
                '      id = "'
                + pin_id
                + '";\n      url = "'
                + nix_escape(url)
                + '";\n      isEssential = true;\n      position = '
                + str(pos_essential)
                + ";"
            )
            if p.get("containerId") is not None:
                frag += "\n      container = " + str(int(p["containerId"])) + ";"
            entries.append((key, frag))
            pos_essential += 1

    for f in folders:
        fid = f.get("id") or ""
        name = (f.get("name") or "").strip() or "Folder"
        space_id = f.get("spaceId") or ""
        nix_space = space_to_key.get(
            space_id, nix_escape(f.get("spaceName") or "Default")
        )
        key = nix_escape(name)
        c = 0
        while key in seen_keys_all:
            c += 1
            key = nix_escape(f"{name}_{c}")
        seen_keys_all.add(key)
        pos = f.get("position", 1000)
        parent_id = f.get("parentId")
        frag = (
            '      id = "'
            + fid
            + '";\n      workspace = spaces."'
            + nix_space
            + '".id;\n      isGroup = true;\n      isFolderCollapsed = true;\n      editedTitle = true;\n      position = '
            + str(pos)
            + ";"
        )
        if parent_id:
            frag += '\n      folderParentId = "' + parent_id + '";'
        entries.append((key, frag))

    for group in windows:
        space_id = group.get("spaceId") or ""
        space_name = group.get("spaceName") or "Default"
        nix_space = space_to_key.get(space_id, nix_escape(space_name))
        for p in group["pins"]:
            if p.get("isEssential"):
                continue
            url = p["url"]
            title = p.get("title") or slug(None, url)
            base_key = slug(title, url)
            key = nix_escape(base_key)
            c = 0
            while key in seen_keys_all:
                c += 1
                key = nix_escape(f"{base_key}_{c}")
            seen_keys_all.add(key)
            pin_id = p.get("tabId") or str(uuid.uuid4()).lower()
            if not re.match(r"^[a-f0-9\-]{36}$", str(pin_id)):
                pin_id = str(uuid.uuid4()).lower()
            folder_id = p.get("folderId")
            frag = (
                '      id = "'
                + pin_id
                + '";\n      url = "'
                + nix_escape(url)
                + '";\n      workspace = spaces."'
                + nix_space
                + '".id;\n      isEssential = false;\n      position = '
                + str(pos_pin)
                + ";"
            )
            if folder_id:
                frag += '\n      folderParentId = "' + folder_id + '";'
            if p.get("containerId") is not None:
                frag += "\n      container = " + str(int(p["containerId"])) + ";"
            pos_pin += 1
            entries.append((key, frag))

    body = "\n".join('    "' + k + '" = {\n' + v + "\n    };" for k, v in entries)
    return (
        f"# Pins and folders (skifli format). Generated by {_SYNC_TOOL}.\n{{ ... }}: let\n  spaces = (import ./spaces.nix {{}}).spaces;\nin {{\n  pinsForce = true;\n  pins = {{\n"
        + body
        + "\n  };\n}\n"
    )


def _write_pins(windows, folders, spaces_list):
    path = os.path.join(_TARGET_PROFILE_DIR, "pins.nix")
    _backup(path)
    content = _render_pins(windows, folders, spaces_list)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {path}", file=sys.stderr)


def main():
    if not os.path.isdir(_TARGET_PROFILE_DIR):
        print(f"Error: profile dir not found: {_TARGET_PROFILE_DIR}", file=sys.stderr)
        sys.exit(1)
    out = load_pinned_per_space()
    spaces_list = out["spaces"]
    windows = out["windows"]
    folders = out.get("folders") or []
    if not spaces_list:
        print("Warning: no spaces in session", file=sys.stderr)
    if not windows:
        print("Warning: no windows/pins in session", file=sys.stderr)
    _write_spaces(spaces_list)
    _write_pins(windows, folders, spaces_list)
    print("Done.", file=sys.stderr)


def compare_flake_to_session():
    if not os.path.isdir(_TARGET_PROFILE_DIR):
        print(f"Error: profile dir not found: {_TARGET_PROFILE_DIR}", file=sys.stderr)
        return 2
    out = load_pinned_per_space()
    spaces_list = out["spaces"]
    windows = out["windows"]
    folders = out.get("folders") or []
    expected_spaces = _render_spaces(spaces_list)
    expected_pins = _render_pins(windows, folders, spaces_list)

    spaces_path = os.path.join(_TARGET_PROFILE_DIR, "spaces.nix")
    pins_path = os.path.join(_TARGET_PROFILE_DIR, "pins.nix")
    actual_spaces = ""
    actual_pins = ""
    if os.path.isfile(spaces_path):
        with open(spaces_path, "r", encoding="utf-8") as f:
            actual_spaces = f.read()
    if os.path.isfile(pins_path):
        with open(pins_path, "r", encoding="utf-8") as f:
            actual_pins = f.read()

    def _print_diff(name, actual, expected, context=3, max_lines=200):
        diff_lines = list(
            unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=f"{name} (flake)",
                tofile=f"{name} (session)",
                lineterm="",
                n=context,
            )
        )
        if not diff_lines:
            return
        print(f"\n--- Diff: {name} ---", file=sys.stderr)
        if len(diff_lines) > max_lines:
            shown = diff_lines[:max_lines]
            print(
                "\n".join(shown)
                + f"\n... (truncated, showing first {max_lines} lines)",
                file=sys.stderr,
            )
            return
        print("\n".join(diff_lines), file=sys.stderr)

    matches = True
    if actual_spaces != expected_spaces:
        matches = False
        print("spaces.nix differs from current Zen session state.", file=sys.stderr)
        _print_diff("spaces.nix", actual_spaces, expected_spaces)
    else:
        print("spaces.nix matches current Zen session state.", file=sys.stderr)
    if actual_pins != expected_pins:
        matches = False
        print("pins.nix differs from current Zen session state.", file=sys.stderr)
        _print_diff("pins.nix", actual_pins, expected_pins)
    else:
        print("pins.nix matches current Zen session state.", file=sys.stderr)

    if matches:
        print("Flake state matches current browser session.", file=sys.stderr)
        return 0
    print("Flake state does not match current browser session.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    main()
