#!/usr/bin/env python3
"""Sync Zen session spaces/pins into flake profile dirs (spaces.nix, pins.nix)."""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
from pathlib import Path

from flake_scripts.lib.common import (
    bad,
    host_is_nixos,
    info,
    resolve_flake_root,
    warn,
)
from flake_scripts.zen.session import (
    iter_space_nix_rows,
    load_pinned_per_space,
    nix_escape,
    normalize_zen_tab_id,
    slug,
)

_FLAKE_ROOT = resolve_flake_root(anchor=Path(__file__))

# Subdirs of modules/profiles/apps/browsers/zen/profiles/ (see zen/default.nix).
_FLAKE_ZEN_PROFILE_PRIMARY = "default"
_FLAKE_ZEN_PROFILE_ALTERNATE = "caya"

_SYNC_TOOL = "zen-sync"


def _truthy_env(name):
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes")


def _nixos_alternate_profile_guard_disabled():
    """Allow writing the alternate flake profile from NixOS when explicitly opted in."""
    return _truthy_env("ZEN_IGNORE_OUTPUT_PROFILE_NIXOS_GUARD") or _truthy_env(
        "ZEN_SYNC_CAYA_ON_NIXOS"
    )


def _resolved_flake_profile_dirname():
    raw = os.environ.get("ZEN_OUTPUT_PROFILE")
    if raw is not None:
        v = raw.strip()
        if v:
            if (
                host_is_nixos()
                and v == _FLAKE_ZEN_PROFILE_ALTERNATE
                and not _nixos_alternate_profile_guard_disabled()
            ):
                return _FLAKE_ZEN_PROFILE_PRIMARY
            return v
    return (
        _FLAKE_ZEN_PROFILE_ALTERNATE
        if sys.platform == "darwin"
        else _FLAKE_ZEN_PROFILE_PRIMARY
    )


def target_profile_dir() -> Path:
    return (
        _FLAKE_ROOT
        / "modules"
        / "profiles"
        / "apps"
        / "browsers"
        / "zen"
        / "profiles"
        / _resolved_flake_profile_dirname()
    )


def _unique_nix_key(base: str, seen: set[str]) -> str:
    key = nix_escape(base)
    c = 0
    while key in seen:
        c += 1
        key = nix_escape(f"{base}_{c}")
    seen.add(key)
    return key


def _render_spaces(spaces_list):
    lines = [
        f'    "{key}" = {{ id = "{sid}"; icon = "{icon}"; position = {pos}; }};'
        for key, sid, icon, pos in iter_space_nix_rows(spaces_list)
    ]
    body = "\n".join(lines)
    return (
        f"# Zen workspaces. Generated by {_SYNC_TOOL}.\n"
        f"{{ ... }}: {{\n"
        f"  spacesForce = true;\n  spaces = {{\n" + body + "\n  };\n}\n"
    )


def _pin_frag(
    *,
    pin_id: str,
    url: str,
    essential: bool,
    position: int,
    nix_space: str | None = None,
    folder_id: str | None = None,
    container_id: int | None = None,
) -> str:
    lines = [
        f'      id = "{pin_id}";',
        f'      url = "{nix_escape(url)}";',
    ]
    if nix_space is not None:
        lines.append(f'      workspace = spaces."{nix_space}".id;')
    lines.append(f"      isEssential = {'true' if essential else 'false'};")
    lines.append(f"      position = {position};")
    if folder_id:
        lines.append(f'      folderParentId = "{folder_id}";')
    if container_id is not None:
        lines.append(f"      container = {int(container_id)};")
    return "\n".join(lines)


def _folder_frag(
    *,
    fid: str,
    nix_space: str,
    position: int,
    parent_id: str | None = None,
) -> str:
    lines = [
        f'      id = "{fid}";',
        f'      workspace = spaces."{nix_space}".id;',
        "      isGroup = true;",
        "      isFolderCollapsed = true;",
        "      editedTitle = true;",
        f"      position = {position};",
    ]
    if parent_id:
        lines.append(f'      folderParentId = "{parent_id}";')
    return "\n".join(lines)


def _render_pins(windows, folders, spaces_list):
    space_to_key = {sid: key for key, sid, _, _ in iter_space_nix_rows(spaces_list)}
    seen_urls_essential = set()
    seen_keys_all = set()
    pos_essential = 101
    pos_pin = 201
    entries = []

    for group in windows:
        for p in group["pins"]:
            if not p.get("isEssential"):
                continue
            url = p["url"]
            if url in seen_urls_essential:
                continue
            seen_urls_essential.add(url)
            title = p.get("title") or slug(None, url)
            key = _unique_nix_key(title or slug(None, url), seen_keys_all)
            pin_id = normalize_zen_tab_id(p.get("tabId"))
            frag = _pin_frag(
                pin_id=pin_id,
                url=url,
                essential=True,
                position=pos_essential,
                container_id=p.get("containerId"),
            )
            entries.append((key, frag))
            pos_essential += 1

    for f in folders:
        fid = f.get("id") or ""
        name = (f.get("name") or "").strip() or "Folder"
        space_id = f.get("spaceId") or ""
        nix_space = space_to_key.get(
            space_id, nix_escape(f.get("spaceName") or "Default")
        )
        key = _unique_nix_key(name, seen_keys_all)
        frag = _folder_frag(
            fid=fid,
            nix_space=nix_space,
            position=f.get("position", 1000),
            parent_id=f.get("parentId"),
        )
        entries.append((key, frag))

    for group in windows:
        space_id = group.get("spaceId") or ""
        space_name = group.get("spaceName") or "Default"
        nix_space = space_to_key.get(space_id, nix_escape(space_name))
        for p in group["pins"]:
            if p.get("isEssential"):
                continue
            url = p["url"]
            title = p.get("title") or slug(None, url)
            base_key = slug(title, url)
            key = _unique_nix_key(base_key, seen_keys_all)
            pin_id = normalize_zen_tab_id(p.get("tabId"))
            frag = _pin_frag(
                pin_id=pin_id,
                url=url,
                essential=False,
                position=pos_pin,
                nix_space=nix_space,
                folder_id=p.get("folderId"),
                container_id=p.get("containerId"),
            )
            pos_pin += 1
            entries.append((key, frag))

    body = "\n".join('    "' + k + '" = {\n' + v + "\n    };" for k, v in entries)
    return (
        f"# Pins and folders (skifli format). Generated by {_SYNC_TOOL}.\n{{ ... }}: let\n  spaces = (import ./spaces.nix {{}}).spaces;\nin {{\n  pinsForce = true;\n  pins = {{\n"
        + body
        + "\n  };\n}\n"
    )


def _nix_fmt(content: str) -> str:
    if not content:
        return content
    proc = subprocess.run(
        ["nixfmt", "-"],
        input=content,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        msg = proc.stderr.strip() or f"exit {proc.returncode}"
        raise RuntimeError(f"nixfmt failed: {msg}")
    return proc.stdout


def _unified_diff(name, actual, expected):
    if actual == expected:
        return []
    return list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=name,
            tofile=f"{name} (session)",
        )
    )


def sync_profile(profile_dir, session, *, check=False, quiet=False):
    spaces_path = profile_dir / "spaces.nix"
    pins_path = profile_dir / "pins.nix"
    spaces_list = session["spaces"]
    expected_spaces = _nix_fmt(_render_spaces(spaces_list))
    expected_pins = _nix_fmt(
        _render_pins(session["windows"], session.get("folders") or [], spaces_list)
    )
    actual_spaces = (
        spaces_path.read_text(encoding="utf-8") if spaces_path.is_file() else ""
    )
    actual_pins = pins_path.read_text(encoding="utf-8") if pins_path.is_file() else ""
    actual_spaces = _nix_fmt(actual_spaces)
    actual_pins = _nix_fmt(actual_pins)
    matches = actual_spaces == expected_spaces and actual_pins == expected_pins
    if not matches and not quiet:
        for name, actual, expected in (
            ("spaces.nix", actual_spaces, expected_spaces),
            ("pins.nix", actual_pins, expected_pins),
        ):
            for line in _unified_diff(name, actual, expected):
                print(line, end="", file=sys.stderr)
    if check:
        if matches:
            if not quiet:
                info("Flake profile matches current Zen session.", stderr=True)
            return 0
        bad("Flake profile does not match current Zen session.", stderr=True)
        return 1
    if matches:
        if not quiet:
            info("Already up to date.", stderr=True)
        return 0
    spaces_path.write_text(expected_spaces, encoding="utf-8")
    pins_path.write_text(expected_pins, encoding="utf-8")
    if not quiet:
        info(f"Wrote {spaces_path}", stderr=True)
        info(f"Wrote {pins_path}", stderr=True)
        info("Done.", stderr=True)
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="zen-sync",
        description="Sync Zen browser session into flake spaces.nix and pins.nix",
    )
    ap.add_argument("--profile", "-p", metavar="DIR", help="Zen browser profile dir")
    ap.add_argument("--check", action="store_true", help="Compare only; no writes")
    ap.add_argument(
        "--quiet", "-q", action="store_true", help="Suppress non-error output"
    )
    args = ap.parse_args(argv)
    if args.profile:
        os.environ["ZEN_PROFILE_ROOT"] = os.path.expanduser(args.profile)
    profile_dir = target_profile_dir()
    if not profile_dir.is_dir():
        bad(f"profile dir not found: {profile_dir}", stderr=True)
        return 1
    session = load_pinned_per_space()
    if not session.get("spaces"):
        warn("no spaces in session", stderr=True)
    if not session.get("windows"):
        warn("no windows/pins in session", stderr=True)
    return sync_profile(profile_dir, session, check=args.check, quiet=args.quiet)


if __name__ == "__main__":
    raise SystemExit(main())
