#!/usr/bin/env python3
"""Write Zen session spaces/pins into flake profile dirs (spaces.nix, pins.nix).

Default target directory under home/.../zen/profiles/ is chosen from the host unless
ZEN_OUTPUT_PROFILE is set. On NixOS, requesting the alternate profile name is remapped
to the primary profile unless ZEN_IGNORE_OUTPUT_PROFILE_NIXOS_GUARD=1 (alias:
ZEN_SYNC_CAYA_ON_NIXOS=1 for compatibility).
"""

import os
import sys
from difflib import unified_diff
from datetime import datetime
from pathlib import Path

from flake_scripts.lib.common import (
    bad,
    console_err,
    host_is_nixos,
    info,
    resolve_flake_root,
    warn,
)
from flake_scripts.zen.extract_pinned_tabs import (
    iter_space_nix_rows,
    load_pinned_per_space,
    nix_escape,
    normalize_zen_tab_id,
    slug,
    space_id_to_nix_keys,
)

_FLAKE_ROOT = resolve_flake_root(anchor=Path(__file__))

# Subdirs of home/shared/apps/browsers/zen/profiles/ (see zen/default.nix).
_FLAKE_ZEN_PROFILE_PRIMARY = "default"
_FLAKE_ZEN_PROFILE_ALTERNATE = "caya"

_SYNC_TOOL = "zen-session sync"

# Not read from the session: opaque workspace gradients break Linux compositor transparency.
# See home/shared/apps/browsers/zen/TRANSPARENCY.md
_TRANSPARENT_WORKSPACE_THEME_LET = """\
  # Workspace gradient themes from Zen are not synced; opaque themes break
  # zen.widget.linux.transparency (brief flash, then solid chrome).
  transparentWorkspaceTheme = {
    type = "gradient";
    colors = [ ];
    opacity = 0.0;
    texture = 0.0;
    rotation = null;
  };
"""


def _truthy_env(name):
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes")


def _nixos_alternate_profile_guard_disabled():
    """Allow writing the alternate flake profile from NixOS when explicitly opted in."""
    return _truthy_env("ZEN_IGNORE_OUTPUT_PROFILE_NIXOS_GUARD") or _truthy_env(
        "ZEN_SYNC_CAYA_ON_NIXOS"
    )


def _resolved_flake_profile_dirname():
    raw = os.environ.get("ZEN_OUTPUT_PROFILE")
    if raw is not None:
        v = raw.strip()
        if v:
            if (
                host_is_nixos()
                and v == _FLAKE_ZEN_PROFILE_ALTERNATE
                and not _nixos_alternate_profile_guard_disabled()
            ):
                return _FLAKE_ZEN_PROFILE_PRIMARY
            return v
    return (
        _FLAKE_ZEN_PROFILE_ALTERNATE
        if sys.platform == "darwin"
        else _FLAKE_ZEN_PROFILE_PRIMARY
    )


_TARGET_PROFILE_DIR = (
    _FLAKE_ROOT
    / "home"
    / "shared"
    / "apps"
    / "browsers"
    / "zen"
    / "profiles"
    / _resolved_flake_profile_dirname()
)


def _backup(path: Path) -> None:
    if not path.is_file():
        return
    stamp = datetime.now().strftime("%Y-%m-%dT%H-%M-%S")
    backup_path = path.parent / f"{path.name}.{stamp}.bak"
    backup_path.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    info(f"Backed up to {backup_path.name}", stderr=True)


def _render_spaces(spaces_list):
    lines = [
        f'    "{key}" = {{ id = "{sid}"; icon = "{icon}"; position = {pos}; theme = transparentWorkspaceTheme; }};'
        for key, sid, icon, pos in iter_space_nix_rows(spaces_list)
    ]
    body = "\n".join(lines)
    return (
        f"# Zen workspaces. Generated by {_SYNC_TOOL}.\n"
        f"{{ ... }}: let\n{_TRANSPARENT_WORKSPACE_THEME_LET}\nin {{\n"
        f"  spacesForce = true;\n  spaces = {{\n" + body + "\n  };\n}\n"
    )


def _write_spaces(spaces_list):
    path = _TARGET_PROFILE_DIR / "spaces.nix"
    _backup(path)
    content = _render_spaces(spaces_list)
    path.write_text(content, encoding="utf-8")
    info(f"Wrote {path}", stderr=True)


def _render_pins(windows, folders, spaces_list):
    space_to_key = space_id_to_nix_keys(spaces_list)
    seen_urls_essential = set()
    seen_keys_all = set()
    pos_essential = 101
    pos_pin = 201
    entries = []

    for group in windows:
        for p in group["pins"]:
            if not p.get("isEssential"):
                continue
            url = p["url"]
            if url in seen_urls_essential:
                continue
            seen_urls_essential.add(url)
            title = p.get("title") or slug(None, url)
            key = nix_escape(title or slug(None, url))
            c = 0
            while key in seen_keys_all:
                c += 1
                key = nix_escape(f"{title or 'Essential'}_{c}")
            seen_keys_all.add(key)
            pin_id = normalize_zen_tab_id(p.get("tabId"))
            frag = (
                '      id = "'
                + pin_id
                + '";\n      url = "'
                + nix_escape(url)
                + '";\n      isEssential = true;\n      position = '
                + str(pos_essential)
                + ";"
            )
            if p.get("containerId") is not None:
                frag += "\n      container = " + str(int(p["containerId"])) + ";"
            entries.append((key, frag))
            pos_essential += 1

    for f in folders:
        fid = f.get("id") or ""
        name = (f.get("name") or "").strip() or "Folder"
        space_id = f.get("spaceId") or ""
        nix_space = space_to_key.get(
            space_id, nix_escape(f.get("spaceName") or "Default")
        )
        key = nix_escape(name)
        c = 0
        while key in seen_keys_all:
            c += 1
            key = nix_escape(f"{name}_{c}")
        seen_keys_all.add(key)
        pos = f.get("position", 1000)
        parent_id = f.get("parentId")
        frag = (
            '      id = "'
            + fid
            + '";\n      workspace = spaces."'
            + nix_space
            + '".id;\n      isGroup = true;\n      isFolderCollapsed = true;\n      editedTitle = true;\n      position = '
            + str(pos)
            + ";"
        )
        if parent_id:
            frag += '\n      folderParentId = "' + parent_id + '";'
        entries.append((key, frag))

    for group in windows:
        space_id = group.get("spaceId") or ""
        space_name = group.get("spaceName") or "Default"
        nix_space = space_to_key.get(space_id, nix_escape(space_name))
        for p in group["pins"]:
            if p.get("isEssential"):
                continue
            url = p["url"]
            title = p.get("title") or slug(None, url)
            base_key = slug(title, url)
            key = nix_escape(base_key)
            c = 0
            while key in seen_keys_all:
                c += 1
                key = nix_escape(f"{base_key}_{c}")
            seen_keys_all.add(key)
            pin_id = normalize_zen_tab_id(p.get("tabId"))
            folder_id = p.get("folderId")
            frag = (
                '      id = "'
                + pin_id
                + '";\n      url = "'
                + nix_escape(url)
                + '";\n      workspace = spaces."'
                + nix_space
                + '".id;\n      isEssential = false;\n      position = '
                + str(pos_pin)
                + ";"
            )
            if folder_id:
                frag += '\n      folderParentId = "' + folder_id + '";'
            if p.get("containerId") is not None:
                frag += "\n      container = " + str(int(p["containerId"])) + ";"
            pos_pin += 1
            entries.append((key, frag))

    body = "\n".join('    "' + k + '" = {\n' + v + "\n    };" for k, v in entries)
    return (
        f"# Pins and folders (skifli format). Generated by {_SYNC_TOOL}.\n{{ ... }}: let\n  spaces = (import ./spaces.nix {{}}).spaces;\nin {{\n  pinsForce = true;\n  pins = {{\n"
        + body
        + "\n  };\n}\n"
    )


def _write_pins(windows, folders, spaces_list):
    path = _TARGET_PROFILE_DIR / "pins.nix"
    _backup(path)
    content = _render_pins(windows, folders, spaces_list)
    path.write_text(content, encoding="utf-8")
    info(f"Wrote {path}", stderr=True)


def main():
    if not _TARGET_PROFILE_DIR.is_dir():
        bad(f"profile dir not found: {_TARGET_PROFILE_DIR}", stderr=True)
        sys.exit(1)
    out = load_pinned_per_space()
    spaces_list = out["spaces"]
    windows = out["windows"]
    folders = out.get("folders") or []
    if not spaces_list:
        warn("no spaces in session", stderr=True)
    if not windows:
        warn("no windows/pins in session", stderr=True)
    _write_spaces(spaces_list)
    _write_pins(windows, folders, spaces_list)
    info("Done.", stderr=True)


def compare_flake_to_session():
    if not _TARGET_PROFILE_DIR.is_dir():
        bad(f"profile dir not found: {_TARGET_PROFILE_DIR}", stderr=True)
        return 2
    out = load_pinned_per_space()
    spaces_list = out["spaces"]
    windows = out["windows"]
    folders = out.get("folders") or []
    expected_spaces = _render_spaces(spaces_list)
    expected_pins = _render_pins(windows, folders, spaces_list)

    spaces_path = _TARGET_PROFILE_DIR / "spaces.nix"
    pins_path = _TARGET_PROFILE_DIR / "pins.nix"
    actual_spaces = (
        spaces_path.read_text(encoding="utf-8") if spaces_path.is_file() else ""
    )
    actual_pins = pins_path.read_text(encoding="utf-8") if pins_path.is_file() else ""

    def _print_diff(name, actual, expected, context=3, max_lines=200):
        diff_lines = list(
            unified_diff(
                actual.splitlines(),
                expected.splitlines(),
                fromfile=f"{name} (flake)",
                tofile=f"{name} (session)",
                lineterm="",
                n=context,
            )
        )
        if not diff_lines:
            return
        console_err.print(f"\n--- Diff: {name} ---", markup=False, highlight=False)
        if len(diff_lines) > max_lines:
            shown = diff_lines[:max_lines]
            text = (
                "\n".join(shown) + f"\n... (truncated, showing first {max_lines} lines)"
            )
            console_err.print(text, markup=False, highlight=False)
            return
        console_err.print("\n".join(diff_lines), markup=False, highlight=False)

    matches = True
    if actual_spaces != expected_spaces:
        matches = False
        warn("spaces.nix differs from current Zen session state.", stderr=True)
        _print_diff("spaces.nix", actual_spaces, expected_spaces)
    else:
        info("spaces.nix matches current Zen session state.", stderr=True)
    if actual_pins != expected_pins:
        matches = False
        warn("pins.nix differs from current Zen session state.", stderr=True)
        _print_diff("pins.nix", actual_pins, expected_pins)
    else:
        info("pins.nix matches current Zen session state.", stderr=True)

    if matches:
        info("Flake state matches current browser session.", stderr=True)
        return 0
    bad("Flake state does not match current browser session.", stderr=True)
    return 1


if __name__ == "__main__":
    main()
