#!/usr/bin/env python3
"""Sync Zen session spaces/pins into flake profile dirs (spaces.nix, pins.nix)."""

from __future__ import annotations

import argparse
import difflib
import os
import subprocess
import sys
from pathlib import Path

from flake_scripts.lib.common import (
    bad,
    host_is_nixos,
    info,
    resolve_flake_root,
    warn,
)
from flake_scripts.zen.session import (
    iter_space_nix_rows,
    load_pinned_per_space,
    nix_escape,
    normalize_zen_tab_id,
    slug,
)

_FLAKE_ROOT = resolve_flake_root(anchor=Path(__file__))

# Subdirs of modules/profiles/apps/browsers/zen/profiles/ (see zen/default.nix).
_FLAKE_ZEN_PROFILE_PRIMARY = "default"
_FLAKE_ZEN_PROFILE_ALTERNATE = "caya"

_SYNC_TOOL = "zen-sync"


def _truthy_env(name):
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes")


def _nixos_alternate_profile_guard_disabled():
    """Allow writing the alternate flake profile from NixOS when explicitly opted in."""
    return _truthy_env("ZEN_IGNORE_OUTPUT_PROFILE_NIXOS_GUARD") or _truthy_env(
        "ZEN_SYNC_CAYA_ON_NIXOS"
    )


def _resolved_flake_profile_dirname():
    raw = os.environ.get("ZEN_OUTPUT_PROFILE")
    if raw is not None:
        v = raw.strip()
        if v:
            if (
                host_is_nixos()
                and v == _FLAKE_ZEN_PROFILE_ALTERNATE
                and not _nixos_alternate_profile_guard_disabled()
            ):
                return _FLAKE_ZEN_PROFILE_PRIMARY
            return v
    return (
        _FLAKE_ZEN_PROFILE_ALTERNATE
        if sys.platform == "darwin"
        else _FLAKE_ZEN_PROFILE_PRIMARY
    )


def target_profile_dir() -> Path:
    return (
        _FLAKE_ROOT
        / "modules"
        / "profiles"
        / "apps"
        / "browsers"
        / "zen"
        / "profiles"
        / _resolved_flake_profile_dirname()
    )


def _unique_nix_key(base: str, seen: set[str]) -> str:
    key = nix_escape(base)
    c = 0
    while key in seen:
        c += 1
        key = nix_escape(f"{base}_{c}")
    seen.add(key)
    return key


def _render_spaces(spaces_list):
    lines = [
        f'    "{key}" = {{ id = "{sid}"; icon = "{icon}"; position = {pos}; }};'
        for key, sid, icon, pos in iter_space_nix_rows(spaces_list)
    ]
    body = "\n".join(lines)
    return (
        f"# Zen workspaces. Generated by {_SYNC_TOOL}.\n"
        f"_: {{\n"
        f"  spacesForce = true;\n  spaces = {{\n" + body + "\n  };\n}\n"
    )


def _pin_frag(
    *,
    pin_id: str,
    url: str,
    essential: bool,
    position: int,
    folder_id: str | None = None,
    container_id: int | None = None,
) -> str:
    lines = [
        f'      id = "{pin_id}";',
        f'      url = "{nix_escape(url)}";',
        f"      isEssential = {'true' if essential else 'false'};",
        f"      position = {position};",
    ]
    if folder_id:
        lines.append(f'      folderParentId = "{folder_id}";')
    if container_id is not None:
        lines.append(f"      container = {int(container_id)};")
    return "\n".join(lines)


def _folder_frag(
    *,
    fid: str,
    position: int,
    parent_id: str | None = None,
) -> str:
    lines = [
        f'      id = "{fid}";',
        "      isGroup = true;",
        "      isFolderCollapsed = true;",
        "      editedTitle = true;",
        f"      position = {position};",
    ]
    if parent_id:
        lines.append(f'      folderParentId = "{parent_id}";')
    return "\n".join(lines)


def _attrset_body(entries) -> str:
    return "\n".join('    "' + k + '" = {\n' + v + "\n    };" for k, v in entries)


def _render_pins(windows, folders, spaces_list):
    """Render pins in the space-scoped form: `spaces.<name>.pins`.

    Essentials stay in the flat `pins` set. With
    `zen.workspaces.separate-essentials = false` they belong to every space, so
    they have no owning space to nest under. Every other pin and folder nests
    under its space, which makes the `workspace = spaces."X".id` pairing
    unnecessary — the module derives it from the owning space.
    """
    space_rows = iter_space_nix_rows(spaces_list)
    space_to_key = {sid: key for key, sid, _, _ in space_rows}
    essentials: list[tuple[str, str]] = []
    scoped: dict[str, list[tuple[str, str]]] = {}
    seen_urls_essential: set[str] = set()
    # Keys are namespaced per space, so equal titles in different spaces keep
    # their name instead of getting a _1 suffix.
    seen_keys: dict[str, set[str]] = {}
    pos_essential = 101
    pos_pin = 201

    def key_for(namespace: str, base: str) -> str:
        return _unique_nix_key(base, seen_keys.setdefault(namespace, set()))

    for group in windows:
        for p in group["pins"]:
            if not p.get("isEssential"):
                continue
            url = p["url"]
            if url in seen_urls_essential:
                continue
            seen_urls_essential.add(url)
            title = p.get("title") or slug(None, url)
            key = key_for("", title or slug(None, url))
            frag = _pin_frag(
                pin_id=normalize_zen_tab_id(p.get("tabId")),
                url=url,
                essential=True,
                position=pos_essential,
                container_id=p.get("containerId"),
            )
            essentials.append((key, frag))
            pos_essential += 1

    for f in folders:
        nix_space = space_to_key.get(
            f.get("spaceId") or "", nix_escape(f.get("spaceName") or "Default")
        )
        key = key_for(nix_space, (f.get("name") or "").strip() or "Folder")
        frag = _folder_frag(
            fid=f.get("id") or "",
            position=f.get("position", 1000),
            parent_id=f.get("parentId"),
        )
        scoped.setdefault(nix_space, []).append((key, frag))

    for group in windows:
        nix_space = space_to_key.get(
            group.get("spaceId") or "", nix_escape(group.get("spaceName") or "Default")
        )
        for p in group["pins"]:
            if p.get("isEssential"):
                continue
            url = p["url"]
            title = p.get("title") or slug(None, url)
            key = key_for(nix_space, slug(title, url))
            frag = _pin_frag(
                pin_id=normalize_zen_tab_id(p.get("tabId")),
                url=url,
                essential=False,
                position=pos_pin,
                folder_id=p.get("folderId"),
                container_id=p.get("containerId"),
            )
            pos_pin += 1
            scoped.setdefault(nix_space, []).append((key, frag))

    ordered = [key for key, _, _, _ in space_rows if key in scoped]
    ordered += [key for key in scoped if key not in set(ordered)]
    space_blocks = "\n".join(
        f'    "{key}" = baseSpaces."{key}" // {{\n      pins = {{\n'
        + _attrset_body(scoped[key])
        + "\n      };\n    };"
        for key in ordered
    )
    spaces_attr = (
        "  spaces = baseSpaces // {\n" + space_blocks + "\n  };\n" if ordered else ""
    )
    return (
        f"# Pins and folders (space-scoped form). Generated by {_SYNC_TOOL}.\n"
        f"# Close Zen before `just switch`: the activation script needs exclusive\n"
        f"# access to zen-sessions.jsonlz4, and silently skips the update otherwise.\n"
        f"_: let\n  baseSpaces = (import ./spaces.nix {{}}).spaces;\nin {{\n"
        f"  pinsForce = true;\n  pins = {{\n"
        + _attrset_body(essentials)
        + "\n  };\n"
        + spaces_attr
        + "}\n"
    )


def _nix_fmt(content: str) -> str:
    if not content:
        return content
    proc = subprocess.run(
        ["nixfmt", "-"],
        input=content,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        msg = proc.stderr.strip() or f"exit {proc.returncode}"
        raise RuntimeError(f"nixfmt failed: {msg}")
    return proc.stdout


def _unified_diff(name, actual, expected):
    if actual == expected:
        return []
    return list(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=name,
            tofile=f"{name} (session)",
        )
    )


def sync_profile(profile_dir, session, *, check=False, quiet=False):
    spaces_path = profile_dir / "spaces.nix"
    pins_path = profile_dir / "pins.nix"
    spaces_list = session["spaces"]
    expected_spaces = _nix_fmt(_render_spaces(spaces_list))
    expected_pins = _nix_fmt(
        _render_pins(session["windows"], session.get("folders") or [], spaces_list)
    )
    actual_spaces = (
        spaces_path.read_text(encoding="utf-8") if spaces_path.is_file() else ""
    )
    actual_pins = pins_path.read_text(encoding="utf-8") if pins_path.is_file() else ""
    actual_spaces = _nix_fmt(actual_spaces)
    actual_pins = _nix_fmt(actual_pins)
    matches = actual_spaces == expected_spaces and actual_pins == expected_pins
    if not matches and not quiet:
        for name, actual, expected in (
            ("spaces.nix", actual_spaces, expected_spaces),
            ("pins.nix", actual_pins, expected_pins),
        ):
            for line in _unified_diff(name, actual, expected):
                print(line, end="", file=sys.stderr)
    if check:
        if matches:
            if not quiet:
                info("Flake profile matches current Zen session.", stderr=True)
            return 0
        bad("Flake profile does not match current Zen session.", stderr=True)
        return 1
    if matches:
        if not quiet:
            info("Already up to date.", stderr=True)
        return 0
    spaces_path.write_text(expected_spaces, encoding="utf-8")
    pins_path.write_text(expected_pins, encoding="utf-8")
    if not quiet:
        info(f"Wrote {spaces_path}", stderr=True)
        info(f"Wrote {pins_path}", stderr=True)
        info("Done.", stderr=True)
    return 0


def main(argv=None):
    ap = argparse.ArgumentParser(
        prog="zen-sync",
        description="Sync Zen browser session into flake spaces.nix and pins.nix",
    )
    ap.add_argument("--profile", "-p", metavar="DIR", help="Zen browser profile dir")
    ap.add_argument("--check", action="store_true", help="Compare only; no writes")
    ap.add_argument(
        "--quiet", "-q", action="store_true", help="Suppress non-error output"
    )
    args = ap.parse_args(argv)
    if args.profile:
        os.environ["ZEN_PROFILE_ROOT"] = os.path.expanduser(args.profile)
    profile_dir = target_profile_dir()
    if not profile_dir.is_dir():
        bad(f"profile dir not found: {profile_dir}", stderr=True)
        return 1
    session = load_pinned_per_space()
    if not session.get("spaces"):
        warn("no spaces in session", stderr=True)
    if not session.get("windows"):
        warn("no windows/pins in session", stderr=True)
    return sync_profile(profile_dir, session, check=args.check, quiet=args.quiet)


if __name__ == "__main__":
    raise SystemExit(main())
