# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to your host configuration instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Temporary root fs to satisfy flake checks. Replace with real values from
  # `nixos-generate-config` on the desktop machine.
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "mode=755" "size=1G" ];
  };

  swapDevices = [ ];

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}

