# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to your host configuration instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # TODO: Run 'nixos-generate-config' on your desktop machine to generate
  # the actual hardware configuration for your specific hardware.
  # 
  # To generate: sudo nixos-generate-config --dir /path/to/flake/hosts/desktop/
  # Then copy the fileSystems, boot, and hardware sections here.

  # Placeholder - REPLACE WITH ACTUAL VALUES FROM YOUR DESKTOP MACHINE
  # fileSystems."/" =
  #   { device = "/dev/disk/by-uuid/YOUR-ROOT-UUID";
  #     fsType = "ext4";
  #   };

  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/YOUR-BOOT-UUID";
  #     fsType = "vfat";
  #     options = [ "fmask=0077" "dmask=0077" ];
  #   };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/YOUR-SWAP-UUID"; }
  #   ];

  # nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}

