# Pins and folders (skifli format). Generated by zen_session.py sync (scripts/zen-session).
{...}: let
  spaces = (import ./spaces.nix {}).spaces;
in {
  pinsForce = true;
  pins = {
    "Inbox | me@jadee.fyi | Proton Mail" = {
      id = "0ba4edca-7793-4f99-bb51-da870b58f8bf";
      url = "https://mail.proton.me/u/1/inbox";
      isEssential = true;
      position = 101;
    };
    "(2) YouTube" = {
      id = "9b78642f-0c6b-4caf-af02-9136b6363b5f";
      url = "https://www.youtube.com/";
      isEssential = true;
      position = 102;
    };
    "I think Tu-95 has enough space inside for way more than 4x FAB-500s or 6x 250s : r/Warthunder" = {
      id = "78d70083-a115-4ea1-a25a-be9bc67ca1df";
      url = "https://www.reddit.com/";
      isEssential = true;
      position = 103;
    };
    "jadee-server/Login" = {
      id = "98dbc3e9-ee34-44a2-8d1a-5539fa7dea98";
      url = "http://jadee-server/login";
      isEssential = true;
      position = 104;
    };
    "Discord - Group Chat That’s All Fun & Games" = {
      id = "5fb91047-d89a-47fd-8a68-0eb8f1ac0f9e";
      url = "https://discord.com/";
      isEssential = true;
      position = 105;
    };
    "WhatsApp" = {
      id = "153b7d18-01a9-4159-abb5-92973ed5318b";
      url = "https://web.whatsapp.com/";
      isEssential = true;
      position = 106;
    };
    "GitHub" = {
      id = "3a024515-6733-42bc-b698-4982f30c2be6";
      url = "https://github.com/";
      isEssential = true;
      position = 107;
    };
    "Le Chat" = {
      id = "f34e2ae1-20bc-4cd3-9ceb-f9b633fd67e2";
      url = "https://chat.mistral.ai/chat";
      isEssential = true;
      position = 108;
    };
    "Home - Mastodon" = {
      id = "9f74dc7f-0ec6-4984-ba38-e9a1b39e092a";
      url = "https://mastodon.social/home";
      workspace = spaces."Home".id;
      isEssential = false;
      position = 201;
    };
    "Bsky" = {
      id = "f1fe4232-6099-4c13-98d8-8578bd5822ac";
      url = "https://bsky.app/";
      workspace = spaces."Home".id;
      isEssential = false;
      position = 202;
    };
  };
}
