{
  config,
  lib,
  hostKey,
  user,
  hostData,
  ...
}: let
  host = hostData.hosts.${hostKey} or {};
  flakePath = "$HOME/.dotfiles/flake";
in {
  # Generate compatibility home.nix for legacy home-manager commands
  # This file is auto-generated from the flake configuration
  home.file.".config/home-manager/home.nix".text = ''
    # This file is automatically generated from ${flakePath}
    # DO NOT EDIT MANUALLY - changes will be overwritten
    #
    # Your actual configuration is in the flake.
    # For commands, use:
    #   home-manager switch --flake ${flakePath}#${hostKey}
    #   home-manager news --flake ${flakePath}#${hostKey}
    #
    # Or use the shell aliases:
    #   hms  - home-manager switch
    #   hmn  - home-manager news
    #   hm   - home-manager (with flake path)

    { config, pkgs, ... }:

    {
      # This file is not used when running with --flake
      # It's only here to prevent error messages from legacy home-manager commands

      home.username = "${user}";
      home.homeDirectory = "${config.home.homeDirectory}";
      home.stateVersion = "${config.home.stateVersion}";

      # Inform the user to use flake commands
      home.file.".home-manager-is-flake".text = '''
        Your home-manager configuration is managed via flake.
        Flake path: ${flakePath}
        Host configuration: ${hostKey}

        Use: home-manager switch --flake ${flakePath}#${hostKey}
        Or:  hms (shell alias)
      ''';
    }
  '';
}
