# Zen workspaces. Generated by zen-session sync.
{...}: {
  spacesForce = true;
  spaces = {
    "Default" = {
      id = "default";
      icon = "";
      position = 1000;
    };
    "Random" = {
      id = "060b1a27-d488-4c97-a51d-333fdac0eb7c";
      icon = "🏠";
      position = 1000;
    };
    "Solutions" = {
      id = "8a4ea01f-fdf1-4f09-9d76-789cbc8e8fc7";
      icon = "💡";
      position = 2000;
    };
    "Work" = {
      id = "4a003f39-c69b-4424-90ae-b2ae49d6e632";
      icon = "📯";
      position = 3000;
    };
    "Development" = {
      id = "8bbf6155-b7cc-4487-9379-35c02d1139ce";
      icon = "💻";
      position = 4000;
    };
    "Research" = {
      id = "278ec41c-2c9d-41b3-aa79-1affeb706629";
      icon = "🔍";
      position = 5000;
    };
  };
}
