# Expose home-manager sops secrets to the user session environment so every
# process started by the user — GUI apps (Zed, niri-spawned apps on Linux;
# apps from Finder/Dock/Spotlight on Darwin) and shells alike — inherits
# them.
#
# Per-platform two-stage activation:
#
#   Linux:
#     1. Write `~/.config/environment.d/50-sops-secrets.conf` (mode 0600).
#        systemd-environment-d-generator picks this up at user manager start.
#     2. `systemctl --user set-environment` for the live session.
#
#   Darwin:
#     1. LaunchAgent `~/Library/LaunchAgents/org.nix-community.home.sops-session-env.plist`
#        runs a wrapper script at login (RunAtLoad=true) that calls
#        `launchctl setenv` for each secret.
#     2. The same wrapper script is invoked during home-manager activation so
#        the live session sees vars without a re-login.
#
# Already-running processes don't pick up updates on either OS — restart them
# (Zed, terminals, etc.) after a switch.
#
# Each sops secret expands to one or more `exports` (var, path, optional
# valuePrefix). The default mapping is `foo-bar` → `FOO_BAR`. The GitHub PAT
# is the only fan-out: one file → `GITHUB_TOKEN`, `GITHUB_PAT`,
# `GITHUB_PERSONAL_ACCESS_TOKEN`, and `NIX_CONFIG=access-tokens = github.com=…`.
{
  config,
  lib,
  pkgs,
  ...
}: let
  secrets = config.sops.secrets or {};
  secretNames = lib.attrNames secrets;

  githubPatSecretAttrs = ["github-token" "gh-token"];

  resolvePath = name: let
    raw = secrets.${name}.path;
  in
    if lib.hasPrefix "/" raw
    then raw
    else "${config.home.homeDirectory}/${raw}";

  defaultEnvVar = name: lib.strings.toUpper (lib.replaceStrings ["-"] ["_"] name);

  mkExports = name: let
    path = resolvePath name;
  in
    if lib.elem name githubPatSecretAttrs
    then [
      {
        inherit path;
        var = "GITHUB_TOKEN";
      }
      {
        inherit path;
        var = "GITHUB_PAT";
      }
      {
        inherit path;
        var = "GITHUB_PERSONAL_ACCESS_TOKEN";
      }
      {
        inherit path;
        var = "NIX_CONFIG";
        valuePrefix = "access-tokens = github.com=";
      }
    ]
    else [
      {
        inherit path;
        var = defaultEnvVar name;
      }
    ];

  exports = lib.concatMap mkExports secretNames;

  esc = lib.escapeShellArg;
  prefixOf = e: e.valuePrefix or "";

  envDir = "${config.home.homeDirectory}/.config/environment.d";
  envFile = "${envDir}/50-sops-secrets.conf";

  emitLinux = e: ''
    if [ -r ${esc e.path} ]; then
      _val=${esc (prefixOf e)}"$(tr -d '[:space:]' <${esc e.path})"
      printf '%s=%s\n' ${esc e.var} "$_val" >>"$envFile"
      systemctl --user set-environment ${esc e.var}="$_val" 2>/dev/null || true
    fi
  '';

  emitDarwin = e: ''
    if [ -r ${esc e.path} ]; then
      _val=${esc (prefixOf e)}"$(tr -d '[:space:]' <${esc e.path})"
      launchctl setenv ${esc e.var} "$_val" 2>/dev/null || true
    fi
  '';

  linuxScript = lib.concatMapStrings emitLinux exports;
  darwinScript = lib.concatMapStrings emitDarwin exports;

  darwinSetenvScript = pkgs.writeShellScript "sops-launchctl-setenv" ''
    set -u
    export PATH=${lib.makeBinPath [pkgs.coreutils]}:/bin:/usr/bin:$PATH
    ${darwinScript}
  '';
in
  lib.mkMerge [
    (lib.mkIf (pkgs.stdenv.isLinux && exports != []) {
      home.activation.sopsSessionEnv = lib.hm.dag.entryAfter ["sops-nix"] ''
        export PATH=${lib.makeBinPath [pkgs.coreutils pkgs.systemd]}:$PATH
        envDir=${esc envDir}
        envFile=${esc envFile}
        mkdir -p "$envDir"
        : >"$envFile"
        chmod 600 "$envFile"
        printf '# Auto-generated by sops-session-env.nix — do not edit.\n' >>"$envFile"

        ${linuxScript}
      '';
    })

    (lib.mkIf (pkgs.stdenv.isDarwin && exports != []) {
      launchd.agents.sops-session-env = {
        enable = true;
        config = {
          ProgramArguments = ["${darwinSetenvScript}"];
          RunAtLoad = true;
          KeepAlive = false;
        };
      };

      home.activation.sopsSessionEnv = lib.hm.dag.entryAfter ["sops-nix"] ''
        ${darwinSetenvScript} || true
      '';
    })
  ]
