# llama.cpp router server (`dotfiles.profiles.llm.serve`). Linux only.
#
# One `llama-server` process in ROUTER mode (`--models-preset`) serves every
# model in `serve.models` on one port and loads them on demand. Each INI
# section name is the OpenAI model id. INI keys are long-form llama-server
# args without the leading `--`. Local preset files accept the full arg set.
# The remote-preset security allowlist does not apply here.
#
# Router and preset mechanics: llama.cpp docs/preset.md and
# tools/server/README.md (PR#17859).
#
# The unit runs as the `llama` system user. Model files land in
# `<stateDir>/huggingface`. Pass the HF token through `environmentFile`.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  llm = config.dotfiles.profiles.llm;
  cfg = llm.serve;
  llamaCpp = llm.llamaCppPackage;

  hfHome = "${cfg.stateDir}/huggingface";
  modelNames = lib.attrNames cfg.models;
  modelsMax = if cfg.modelsMax != null then cfg.modelsMax else lib.length modelNames;

  renderValue =
    v:
    if lib.isBool v then
      (if v then "true" else "false")
    else if lib.isInt v then
      toString v
    else
      v;

  # Fixed key order, then the free-form `settings` (alphabetical).
  renderModel =
    name: m:
    let
      hfRepo = if m.quant != null then "${m.hfRepo}:${m.quant}" else m.hfRepo;
      keyed = lib.concatLists [
        [ "hf-repo = ${hfRepo}" ]
        (lib.optional m.mmprojAuto "mmproj-auto = true")
        (lib.optional m.embedding "embedding = true")
        (lib.optional (m.pooling != null) "pooling = ${m.pooling}")
        [ "ctx-size = ${toString m.ctx}" ]
        (lib.optional (m.slots != null) "parallel = ${toString m.slots}")
        (lib.optionals (m.kvType != null) [
          "cache-type-k = ${m.kvType}"
          "cache-type-v = ${m.kvType}"
        ])
        [ "n-gpu-layers = ${toString cfg.gpuLayers}" ]
        (lib.optional (m.flashAttn != null) "flash-attn = ${m.flashAttn}")
        (lib.mapAttrsToList (k: v: "${k} = ${renderValue v}") m.settings)
      ];
    in
    ''
      [${name}]
      ${lib.concatStringsSep "\n" keyed}
    '';

  presetsIni = pkgs.writeText "llama-cpp-presets.ini" ''
    # Generated by modules/profiles/llm/serve.nix from dotfiles.profiles.llm.serve. Do not edit by hand.
    # Section = OpenAI model id; keys = llama-server long args minus the leading "--".

    ${lib.concatStringsSep "\n" (lib.mapAttrsToList renderModel cfg.models)}'';

  serveArgs = [
    "${llamaCpp}/bin/llama-server"
    "--host"
    cfg.host
    "--port"
    (toString cfg.port)
    "--models-preset"
    "${presetsIni}"
    "--models-max"
    (toString modelsMax)
  ]
  ++ lib.optionals (cfg.threads != null) [
    "--threads"
    (toString cfg.threads)
  ];
in
{
  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = modelNames != [ ];
        message = "dotfiles.profiles.llm.serve.enable needs at least one entry in serve.models.";
      }
    ];

    # The CLI (`llama-server --list-devices`, `llama-bench`) and the `hf` CLI
    # for cache inspection, on PATH for on-box ops.
    environment.systemPackages = [
      llamaCpp
      pkgs.python314Packages.huggingface-hub
    ];

    users.users.llama = {
      isSystemUser = true;
      group = "llama";
      home = cfg.stateDir;
      createHome = false;
      extraGroups = [
        "render"
        "video"
      ];
    };
    users.groups.llama = { };

    systemd.tmpfiles.rules = [
      "d ${cfg.stateDir} 0750 llama llama - -"
      "d ${hfHome} 0750 llama llama - -"
    ];

    systemd.services.llama-cpp = {
      description = "llama.cpp router: ${lib.concatStringsSep ", " modelNames}";
      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      environment = {
        HF_HOME = hfHome;
      }
      // lib.optionalAttrs (cfg.device != null) {
        LLAMA_ARG_DEVICE = cfg.device;
      };

      serviceConfig = {
        Type = "simple";
        User = "llama";
        Group = "llama";

        ExecStart = lib.escapeShellArgs serveArgs;

        Restart = "on-failure";
        RestartSec = 10;
        TimeoutStartSec = 0;

        DeviceAllow = [ "char-drm rw" ];
        PrivateDevices = false;

        WorkingDirectory = cfg.stateDir;

        ProtectSystem = "strict";
        ProtectHome = true;
        NoNewPrivileges = true;
        ReadWritePaths = [ cfg.stateDir ];
      }
      // lib.optionalAttrs (cfg.environmentFile != null) {
        EnvironmentFile = cfg.environmentFile;
      };
    };
  };
}
