# llama.cpp Vulkan — the "llamacpp" backend of the local chat stack (selected via
# `host.miniLlmBackend = "llamacpp"` in `host.nix`; the "vllm" alternative is
# `./vllm-xpu.nix`). Shared GPU stack + HF token: `./default.nix`.
#
# Runs in llama-server's ROUTER mode (`--models-preset`): one process on :8000 serves
# multiple model presets and loads them on demand. Two presets today, both resident
# (`--models-max 2`), each an OpenAI model id:
#   [local-chat]  unsloth/gemma-4-12B-it-qat-GGUF — Gemma 4 12B QAT (UD-Q4_K_XL) +
#                 vision (mmproj-*.gguf). MTP speculative decoding is wired but gated
#                 off (`chatMtp`) until nixpkgs llama.cpp ships the gemma4-assistant
#                 draft arch — see the chatMtp note below.
#   [local-embed] mradermacher/F2LLM-v2-0.6B-GGUF — Qwen3-arch embedding model
#                 (`embedding = true`), for /v1/embeddings.
# `local-chat` keeps the shared chat contract (host.miniLlmServedName), so open-webui
# is unaffected; `local-embed` (host.miniLlmEmbedServedName) is the extra
# embedding capability (vLLM backend does not serve it). See docs/hosts/mini-llm-hosting.md.
#
# Router/preset mechanics: docs/preset.md + tools/server/README.md (PR#17859). Section
# name = the served model id; keys are long-form llama-server args minus `--`. Local
# preset files allow the full arg set (the security allowlist is remote-presets-only).
{
  config,
  lib,
  pkgs,
  host,
  ...
}:
let
  llamaCpp = pkgs.llama-cpp.override { vulkanSupport = true; };

  port = host.miniLlmPort;
  listenHost = host.miniLlmHost;
  chatName = host.miniLlmServedName;
  embedName = host.miniLlmEmbedServedName;

  # --- chat preset (Gemma 4 12B QAT + MTP + vision) ---------------------------
  chatRepo = "unsloth/gemma-4-12B-it-qat-GGUF";
  chatQuant = "UD-Q4_K_XL";
  # KV budget on the 15 GiB Arc B50 with MTP off (no ~2 GB drafter): QAT ~6.7 + mmproj
  # ~1 + embedder ~0.6 + overhead ~1.5 ≈ 9.8 GB used, leaving ~5.2 GB for chat KV.
  # Gemma 4 is cheap on KV (only 8 of 48 layers are full-attention; the rest cap at a
  # 1024 sliding window), ~32 KiB/token at q8_0 → 128K ≈ 4.2 GB, ~1 GB margin. `chatCtx`
  # is the TOTAL pool split across `chatSlots` (each conversation gets chatCtx/chatSlots).
  # Verify on the box (journalctl prints KV size; intel_gpu_top shows VRAM) — there is
  # room to push higher toward the model's 256K train length if it holds. Re-enabling
  # MTP later reclaims ~2 GB, so drop chatCtx back toward 64K then.
  chatCtx = 131072; # 128K total → 64K per conversation at 2 slots
  chatSlots = 2;
  chatKvType = "q8_0";
  # MTP speculative decoding for Gemma 4 needs the `gemma4-assistant` draft arch, added
  # in llama.cpp PR #23398 (2026-06-07). The nixpkgs build (commit e3ba22d) ships the
  # `--spec-type draft-mtp` *flag* but NOT that arch loader, so the drafter fails with
  # "unknown model architecture: 'gemma4-assistant'" and the server exits at load. Keep
  # off until nixpkgs llama-cpp is new enough, then flip to true. (Off also frees the
  # ~2 GB drafter, leaving headroom to raise chatCtx.)
  chatMtp = false;
  embedRepo = "mradermacher/F2LLM-v2-0.6B-GGUF";
  embedQuant = "Q8_0";
  embedCtx = 8192;
  embedPooling = "last";

  gpuLayers = 999;
  hfHome = "${stateDir}/huggingface";
  stateDir = "/var/lib/llama-cpp";

  # MTP preset lines, emitted only when chatMtp. Blank otherwise (INI ignores blank lines).
  chatSpecLines = lib.optionalString chatMtp "spec-type = draft-mtp\nspec-draft-n-max = 2";

  presetsIni = pkgs.writeText "llama-cpp-presets.ini" ''
    # Generated by hosts/mini/services/llm/llama-cpp.nix — do not edit by hand.
    # Section = OpenAI model id; keys = llama-server long args minus the leading "--".

    [${chatName}]
    hf-repo = ${chatRepo}:${chatQuant}
    mmproj-auto = true
    ${chatSpecLines}
    ctx-size = ${toString chatCtx}
    parallel = ${toString chatSlots}
    cache-type-k = ${chatKvType}
    cache-type-v = ${chatKvType}
    n-gpu-layers = ${toString gpuLayers}
    flash-attn = on
    jinja = true
    temp = 1.0
    top-p = 0.95
    top-k = 64

    [${embedName}]
    hf-repo = ${embedRepo}:${embedQuant}
    embedding = true
    pooling = ${embedPooling}
    ctx-size = ${toString embedCtx}
    n-gpu-layers = ${toString gpuLayers}
  '';

  serveArgs = [
    "${llamaCpp}/bin/llama-server"
    "--host"
    listenHost
    "--port"
    (toString port)
    "--models-preset"
    "${presetsIni}"
    "--models-max"
    "2"
    "--threads"
    "8"
  ];
in
{
  environment.systemPackages = [ llamaCpp ];

  users.users.llama = {
    isSystemUser = true;
    group = "llama";
    home = stateDir;
    createHome = false;
    extraGroups = [
      "render"
      "video"
    ];
  };
  users.groups.llama = { };

  systemd.tmpfiles.rules = [
    "d ${stateDir} 0750 llama llama - -"
    "d ${hfHome} 0750 llama llama - -"
  ];

  systemd.services.llama-cpp-gemma = {
    description = "llama.cpp router — ${chatName} (gemma-4-12B QAT+MTP) + ${embedName} (F2LLM-v2-0.6B)";
    wantedBy = [ "multi-user.target" ];
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];

    environment = {
      HF_HOME = hfHome;
    };

    serviceConfig = {
      Type = "simple";
      User = "llama";
      Group = "llama";

      ExecStart = lib.escapeShellArgs serveArgs;

      Restart = "on-failure";
      RestartSec = 10;
      TimeoutStartSec = 0;

      DeviceAllow = [ "char-drm rw" ];
      PrivateDevices = false;

      WorkingDirectory = stateDir;

      ProtectSystem = "strict";
      ProtectHome = true;
      NoNewPrivileges = true;
      ReadWritePaths = [ stateDir ];

      EnvironmentFile = config.sops.templates."mini-llm-hf.env".path;
    };
  };
}
