config_version = 8

[backdrop]
enabled = true

[bar]
order = [ "default", "side" ]

    [bar.default]
    background_opacity = 0.65000000000000002
    capsule_radius = 6
    capsule_thickness = 0.69999999999999996
    center = [ "group:g3" ]
    enabled = false
    end = [ "tray", "group:g2", "group:g4" ]
    margin_ends = 900
    margin_opposite_edge = 5
    padding = 20
    radius = 5
    reserve_space = false
    show_on_workspace_switch = false
    start = [ "tailscale_2", "group:g1" ]
    thickness = 25

        [bar.default.monitor.DP-1]
        enabled = true

        [[bar.default.capsule_group]]
        border = ""
        enabled = true
        fill = "on_primary"
        id = "g1"
        members = [ "clipboard", "recorder", "screenshot", "privacy" ]
        opacity = 0.59999999999999998
        padding = 6.0

        [[bar.default.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "control-center", "notifications", "volume", "session" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.default.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "active_window" ]
        opacity = 1.0
        padding = 6.0
        radius = 6.0

        [[bar.default.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "clock" ]
        opacity = 1.0
        padding = 6.0
        radius = 6.0

    [bar.side]
    background_opacity = 0.69999999999999996
    capsule_radius = 6
    capsule_thickness = 0.69999999999999996
    center = [ "group:g4" ]
    enabled = false
    end = [ "group:g6", "group:g1" ]
    margin_edge = 10
    margin_ends = 10
    padding = 6
    radius = 5
    start = [ "group:g5", "group:g2", "group:g3" ]
    thickness = 45

        [bar.side.monitor.HDMI-A-1]
        enabled = true

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "network_tx", "network_rx" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "ram", "temp", "cat", "cpu" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "clock", "date" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "media", "audio_visualizer" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g5"
        members = [ "keyboard_layout" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g6"
        members = [ "weather" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 15

[control_center]
hidden_tabs = [ "bluetooth" ]

    [[control_center.shortcuts]]
    type = "system"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "dark_mode"

    [[control_center.shortcuts]]
    type = "keyboard_layout"

    [[control_center.shortcuts]]
    type = "jadeezomg/tailscale:toggle"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 208.0
    box_width = 432.0
    cx = 1431.0
    cy = 157.0
    output = "HDMI-A-1"
    rotation = -0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        hide_when_no_media = true
        layout = "horizontal"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 112.0
    box_width = 288.0
    cx = 1407.0
    cy = 357.0
    output = "HDMI-A-1"
    rotation = -0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        display = "graph"
        shadow = true
        show_label = true
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 96.0
    box_width = 272.0
    cx = 1175.0
    cy = 597.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        show_forecast = true

[location]
auto_locate = true

[lockscreen]
monitors = [ "DP-1" ]

[lockscreen_widgets]
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 1280.0
    cy = 1241.5
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 229.0
    box_width = 810.0
    cx = 831.0
    cy = 2755.5
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_weather = true

[notification]
monitors = [ "HDMI-A-1" ]

[osd]
background_opacity = 0.54999998770654202
monitors = [ "DP-1" ]
offset_y = 40

[plugin_settings."kenn/keybind-cheatsheet"]
compositor = "niri"

[plugin_settings."noctalia/screen_recorder"]
copy_to_clipboard = true
video_codec = "hevc"

[plugin_settings."noctalia/tailscale"]
close_on_copy = true
panel_height = 502
panel_width = 390
ssh_user = "jadee"

[plugins]
auto_update = true
enabled = [ "dotnetrob/cat", "kenn/keybind-cheatsheet", "noctalia/screen_recorder", "jadeezomg/tailscale" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    kind = "path"
    location = "~/Git/community-plugins"
    name = "community-plugins-fork"

[shell]
app_icon_color = "primary"
avatar_path = "/home/jadee/Pictures/Images/L1410618-crop.jpeg"
button_borders = false
card_borders = false
corner_radius_scale = 0.5000000074505806
font_family = "Inter Display"
input_borders = false
password_style = "random"
popup_borders = false
popup_shadows = false

    [shell.animation]
    speed = 1.5000000223517418

    [shell.panel]
    clipboard_placement = "attached"
    polkit_placement = "attached"
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [shell.screen_corners]
    enabled = true
    size = 15

    [shell.shadow]
    alpha = 0.24999999441206455

[theme]
builtin = "Gruvbox"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/jadee/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/jadee/Pictures/Wallpapers/Hugo_Charlemont_Bauerngarten.jpg"

    [wallpaper.last]
    path = "/home/jadee/Pictures/Wallpapers/Hugo_Charlemont_Bauerngarten.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/jadee/Pictures/Wallpapers/Hugo_Charlemont_Bauerngarten.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/jadee/Pictures/Wallpapers/Hugo_Charlemont_Bauerngarten.jpg"

[widget.active_window]
anchor = true
icon_size = 15

[widget.audio_visualizer]
bands = 35
color_1 = "secondary"
mirrored = false
width = 150

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.control-center]
glyph = "snowflake"

[widget.cpu]
display = "text"
label_min_width = 30

[widget.keyboard_layout.custom_labels]
"English (US, intl., with dead keys)" = "en"
German = "de"

[widget.media]
anchor = true
art_size = 70
hide_when_no_media = true
max_length = 300
min_length = 150
title_scroll = "on_hover"

[widget.network_rx]
display = "graph"
label_min_width = 60

[widget.network_tx]
display = "graph"
label_min_width = 60

[widget.privacy]
hide_inactive = true

[widget.ram]
display = "text"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.tailscale_2]
show_ip = false
type = "jadeezomg/tailscale:tailscale"

[widget.taskbar]
enabled = false
focused_output_only = true
group_by_workspace = true
hide_empty_workspaces = true
inactive_opacity = 0.75
minimal = true
workspace_label_placement = "inside"

[widget.temp]
display = "text"

[widget.tray]
drawer = true
drawer_columns = 5
drawer_item_size = 20.0
hidden = [ "Network" ]

[widget.volume]
mute_color = "secondary"
show_label = false

[widget.workspaces]
enabled = false
hide_when_empty = true
style = "focus_hint"