config_version = 13

[backdrop]
enabled = true

[bar]
order = [ "default", "side", "laptop" ]

    [bar.default]
    background_opacity = 0.65000000000000002
    capsule_radius = 6
    capsule_thickness = 0.69999999999999996
    center = [ "group:g3" ]
    enabled = false
    end = [ "tray", "group:g2", "group:g4" ]
    margin_ends = 900
    margin_opposite_edge = 5
    padding = 20
    radius = 5
    reserve_space = false
    show_on_workspace_switch = false
    start = [ "status", "group:g1" ]
    thickness = 25

        [bar.default.monitor.DP-1]
        enabled = true

        [bar.default.monitor.DP-2]
        enabled = true

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "on_primary"
        id = "g1"
        members = [ "clipboard", "recorder", "screenshot", "launcher_2", "privacy" ]
        opacity = 0.60000002384185791
        padding = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "control-center", "bar_3", "notifications", "volume", "session" ]
        opacity = 0.60000002384185791
        padding = 6.0
        radius = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "active_window" ]
        opacity = 1.0
        padding = 6.0
        radius = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "clock" ]
        opacity = 1.0
        padding = 6.0
        radius = 6.0

    [bar.laptop]
    capsule_radius = 6
    capsule_thickness = 0.69999999999999996
    center = [ "active_window" ]
    enabled = false
    end = [ "tray", "group:g5", "group:g2", "group:g4" ]
    margin_ends = 600
    padding = 20
    radius = 5
    reserve_space = false
    show_on_workspace_switch = false
    start = [ "status_2", "group:g1", "group:g6", "media" ]
    thickness = 25

        [bar.laptop.monitor.eDP-1]
        enabled = true

        [[bar.laptop.capsule_group]]
        accordion = true
        accordion_direction = "end"
        border = ""
        enabled = true
        fill = "on_primary"
        id = "g1"
        members = [ "clipboard", "recorder", "screenshot", "privacy" ]
        opacity = 0.60000002384185791
        padding = 6.0

        [[bar.laptop.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "control-center", "bar_2", "notifications", "session" ]
        opacity = 0.60000002384185791
        padding = 6.0
        radius = 6.0

        [[bar.laptop.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "weather", "clock" ]
        opacity = 0.60000002384185791
        padding = 6.0
        radius = 6.0

        [[bar.laptop.capsule_group]]
        accordion = true
        accordion_direction = "start"
        enabled = true
        fill = "surface_variant"
        id = "g5"
        members = [ "power_profile", "network", "bluetooth", "volume", "brightness" ]
        opacity = 0.60000002384185791
        padding = 6.0
        radius = 6.0

        [[bar.laptop.capsule_group]]
        accordion = false
        accordion_direction = "end"
        enabled = true
        fill = "surface_variant"
        id = "g6"
        members = [ "battery", "cpu" ]
        opacity = 0.60000002384185791
        padding = 6.0
        radius = 6.0

    [bar.side]
    background_opacity = 0.69999999999999996
    capsule_radius = 6
    capsule_thickness = 0.69999999999999996
    center = [ "group:g4" ]
    enabled = false
    end = [ "group:g6", "group:g1" ]
    margin_edge = 10
    margin_ends = 10
    padding = 6
    radius = 5
    start = [ "group:g5", "group:g2", "group:g3" ]
    thickness = 45

        [bar.side.monitor.HDMI-A-1]
        enabled = true

        [bar.side.monitor.HDMI-A-2]
        enabled = true

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "network_tx", "network_rx" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g3"
        members = [ "ram", "temp", "cat", "cpu" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "clock", "date" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g4"
        members = [ "media", "audio_visualizer" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g5"
        members = [ "keyboard_layout" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

        [[bar.side.capsule_group]]
        enabled = true
        fill = "surface_variant"
        id = "g6"
        members = [ "weather" ]
        opacity = 0.59999999999999998
        padding = 6.0
        radius = 6.0

[battery.device."/org/freedesktop/UPower/devices/battery_hidpp_battery_0"]
warning_threshold = 15

[control_center]
hidden_tabs = []

    [[control_center.shortcuts]]
    type = "system"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "keyboard_layout"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "jadeezomg/tailscale:toggle"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 208.0
    box_width = 432.0
    cx = 1431.0
    cy = 157.0
    output = "HDMI-A-1"
    placement_height = 2954.0
    placement_width = 1662.0
    rotation = -0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        hide_when_no_media = true
        layout = "horizontal"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 112.0
    box_width = 288.0
    cx = 1407.0
    cy = 357.0
    output = "HDMI-A-1"
    placement_height = 2954.0
    placement_width = 1662.0
    rotation = -0.0
    type = "sysmon"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = true
        display = "graph"
        shadow = true
        show_label = true
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 96.0
    box_width = 272.0
    cx = 1175.0
    cy = 597.0
    output = "HDMI-A-1"
    placement_height = 2954.0
    placement_width = 1662.0
    rotation = 0.0
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        show_forecast = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 30

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 420.0

[location]
auto_locate = true

[lockscreen]
monitors = [ "eDP-1" ]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-login-box@DP-2",
    "lockscreen-login-box@HDMI-A-2",
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@HDMI-A-1"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1241.5
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 831.0
    cy = 2755.5
    output = "HDMI-A-1"
    placement_height = 2954.0
    placement_width = 1662.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 831.0
    cy = 2772.0
    output = "HDMI-A-2"
    placement_height = 2954.0
    placement_width = 1662.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 1098.0
    output = "eDP-1"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.59999998658895493
border = false
monitors = [ "HDMI-A-1", "eDP-1" ]

[osd]
background_opacity = 0.59999998658895493
border = false
monitors = [ "DP-1", "eDP-1" ]
offset_y = 40

[plugin_settings."alexander/game-launcher"]
browser_open_near_click = false
browser_placement = "attached"
lutris_enabled = false

[plugin_settings."davemhammer/tailscale"]
manager_open_near_click = false
manager_placement = "attached"

[plugin_settings."icefish/phone-connect"]
details_floating_placement = "attached"
details_open_near_click = false
details_widget_open_near_click = false
details_widget_placement = "attached"

[plugin_settings."kenn/keybind-cheatsheet"]
compositor = "niri"

[plugin_settings."noctalia/screen_recorder"]
copy_to_clipboard = true
video_codec = "hevc"

[plugin_settings."noctalia/tailscale"]
close_on_copy = true
panel_height = 502
panel_width = 390
ssh_user = "jadee"

[plugins]
auto_update = "all"
enabled = [
    "noctalia/screen_recorder",
    "jadeezomg/tailscale",
    "davemhammer/tailscale",
    "alexander/game-launcher",
    "dotnetrob/cat",
    "kenn/keybind-cheatsheet",
    "icefish/phone-connect"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

    [[plugins.source]]
    enabled = false
    kind = "path"
    location = "~/Git/community-plugins"
    name = "community-plugins-fork"

[shell]
app_icon_color = "primary"
avatar_path = "/home/jadee/Pictures/Images/L1410618-crop.jpeg"
corner_radius_scale = 0.5000000074505806
font_family = "Inter Display"
password_style = "random"
popup_shadows = true

    [shell.animation]
    speed = 1.5000000223517418

    [shell.keyboard_layout.custom_labels]
    "English (US, intl., with dead keys)" = "en"
    German = "de"

    [shell.panel]
    borders = false
    clipboard_placement = "attached"
    floating_offset = 10
    polkit_placement = "attached"
    transparency_mode = "glass"
    wallpaper_placement = "attached"

    [shell.screen_corners]
    enabled = true
    size = 15

    [shell.session]
    grid = true

    [shell.shadow]
    alpha = 0.24999999441206455

[theme]
builtin = "Gruvbox"

    [theme.templates]
    enable_builtin_templates = false
    enable_community_templates = false

[wallpaper]
directory = "/home/jadee/Pictures/Wallpapers"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/jadee/Pictures/Wallpapers/2021_CKS_20061_0018_001(henriette_gudin_the_bronze_horseman092943).jpg"

    [wallpaper.last]
    path = "/home/jadee/Pictures/Wallpapers/2021_CKS_20061_0018_001(henriette_gudin_the_bronze_horseman092943).jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/jadee/Pictures/Wallpapers/2021_CKS_20061_0018_001(henriette_gudin_the_bronze_horseman092943).jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/jadee/Pictures/Wallpapers/Sunrise over Fishing Waters--Maine William E. Norton.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/jadee/Pictures/Wallpapers/2021_CKS_20061_0018_001(henriette_gudin_the_bronze_horseman092943).jpg"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/jadee/Pictures/Wallpapers/Sunrise over Fishing Waters--Maine William E. Norton.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/jadee/Pictures/Wallpapers/Sunrise over Fishing Waters--Maine William E. Norton.jpg"

[widget.active_window]
anchor = true
capsule_opacity = 0.59999999999999998
icon_size = 15
max_length = 150
min_length = 100
title_scroll = "on_hover"

[widget.audio_visualizer]
bands = 35
color_1 = "secondary"
mirrored = false
width = 150

[widget.bar]
type = "icefish/phone-connect:bar"

[widget.bar_2]
type = "icefish/phone-connect:bar"

[widget.bar_3]
type = "icefish/phone-connect:bar"

[widget.brightness]
show_label = false

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.control-center]
glyph = "snowflake"

[widget.cpu]
display = "text"
label_min_width = 30
stat = "cpu_temp"
visualization = "none"

[widget.keyboard_layout]

[widget.launcher_2]
type = "alexander/game-launcher:launcher"

[widget.media]
album_art_only = true
anchor = false
art_size = 45
capsule = true
capsule_padding = 0
max_length = 200

[widget.network]
show_label = false
vpn_status = "both"

[widget.network_rx]
display = "graph"
label_min_width = 60

[widget.network_tx]
display = "graph"
label_min_width = 60

[widget.privacy]
hide_inactive = true

[widget.ram]
display = "text"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.status]
capsule_opacity = 0.59999999999999998
show_counts = false
type = "davemhammer/tailscale:status"

[widget.status_2]
show_counts = false
type = "davemhammer/tailscale:status"

[widget.taskbar]
enabled = false
focused_output_only = true
group_by_workspace = true
hide_empty_workspaces = true
inactive_opacity = 0.75
minimal = true
workspace_label_placement = "inside"

[widget.temp]
display = "text"

[widget.tray]
drawer = true
drawer_columns = 5
drawer_item_size = 20.0
hidden = [ "Network" ]

[widget.volume]
mute_color = "secondary"
show_label = false

[widget.weather]
show_condition = false

[widget.workspaces]
enabled = false
hide_when_empty = true
style = "focus_hint"