# GENERATED by darwin-defaults. DO NOT EDIT.
# Sync: just darwin-defaults-sync
# Check: just darwin-defaults-check
# Empty until the first sync on macOS (caya).
{ ... }: {
  targets.darwin.defaults = { };
}
